import{i as c,S as u}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const d="44946151-dc02d84f49eea13b7d5c48659",m="https://pixabay.com/api/";document.querySelector(".search-btn");const f=document.querySelector(".search-form"),g=document.querySelector(".input-field");document.querySelector(".gallery-result");const l=document.querySelector(".gallery-result-list");document.querySelector(".loading-text");f.addEventListener("submit",s=>{s.preventDefault();const o=g.value;p(o)});function p(s){const o=`${m}?key=${d}&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true`;a.enable(),fetch(o).then(r=>{if(!r.ok)throw new Error(`Error! status: ${r.status}`);return r.json()}).then(r=>{a.disable(),r.hits?h(r.hits):c.warning({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",messageColor:"#fff"})}).catch(r=>{a.disable(),console.error(r),c.warning({title:"Error",message:"An error occurred while fetching images"})})}const y="Sorry, there are no images matching your search query. Please try again!";function h(s){if(l.innerHTML="",s.length===0){c.warning({message:y,backgroundColor:"#ef4040",messageColor:"#fff"});return}const o=s.map(b).join("");l.insertAdjacentHTML("beforeend",o)}function b({webformatURL:s,tags:o,downloads:r,likes:n,comments:e,views:t}){return`<li class="list-container">
    <div class="image-container">
      <img src="${s}" alt="${o}" />
      <div class="descr-element">
        <p>"views ${t} dowmloads ${r} likes ${n} comments ${e}"</p>
      </div>
    </div>
  </li>`}const L={captions:!0,captionsData:"alt",captionDelay:250,close:!0,className:"simpleLightboxGallery",doubleTapZoom:2,scrollZoom:!0,overlay:!0};new u(".gallery-result-list ul li div img",L);const a={enable:()=>document.querySelector(".spinner").classList.remove("disabled"),disable:()=>document.querySelector(".spinner").classList.add("disabled")};
//# sourceMappingURL=commonHelpers.js.map
